[theme]
base="dark"
primaryColor="#8b5cf6"
backgroundColor="#06060f"
secondaryBackgroundColor="#11111a"
textColor="#f9fafb"
font="sans serif"

[client]
showSidebarNavigation = false

[runner]
fastReruns = true
